theme: jekyll-theme-cayman
lang: en-US

title: FC Studio
description: Making a difference in the mobile application ecosystem.

show_downloads: false
google_analytics: UA-167983636-1

github:
  build_revision: 0.0.1


